app.name: Template Spring MVC Empty Project
app.description: ${app.name} is a Spring Boot app
app.version: 0.1-SNAPSHOT

spring.main.show-banner: false

error.whitelabel.enabled: true

logging.level.org.springframework: WARN
logging.level.org.springframework.web: WARN
logging.level.org.hibernate: WARN
logging.level.org.thymeleaf: WARN
