app:
    name: Template Spring MVC wint AngularJS Empty Project
    description: ${app.name} is a Spring Boot app
    version: 0.1-SNAPSHOT

spring:
    main.show-banner: false

error.whitelabel.enabled: true

logging:
    level:
        org:
            springframework: INFO
            springframework.web: INFO
            springframework.test: INFO
            hibernate: INFO
